### PR TITLE
Fixes #10 {added wavy background}

### LINKED ISSUE #10: Add static wave design frontend component
### Feature request-
Make sure the code is simple to understand and easy to use.

You don't have to replicate it exactly like this, this is just for example-

https://user-images.githubusercontent.com/54665036/120937549-b0489500-c72b-11eb-9c55-d49738fed39f.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by starrohan999**
## What is the change?
added wavy background file in background folder

## Related issue?
closes: #issue 2

## How was it tested?
I tested all code

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

## GIF you created:

2021-06-11-18-05-24-online-video-min

### CODE REVIEW

**Comment by starrohan999** [comment]
hey @Pranav016  sir please review it.

**Comment by starrohan999** [comment]
is this correct repo for LGM soc-21

**Review by Pranav016 — APPROVED** [review]
Excellent work. 
Just one suggestion from my side is to improve the commit message, either mention the work done in the commit message or if you are mentioning the issue then do `#issue-number` because that will add a hyperlink of the issue to the commit message.

**Comment by Pranav016** [comment]
Solves issue #10

**Comment by starrohan999** [comment]
Thank you so much @Pranav016.
Next time I will do a commit my message in your way.

**Comment by Pranav016** [comment]
@all-contributors please add @starrohan999 for code

**Comment by Pranav016** [comment]
@all-contributors please add @starrohan999 for doc

**Pull request merged**
