### PR TITLE
Siddhi/progressbar

### LINKED ISSUE #210: Animated progress Bar
### Feature request-
Dynamic animated progress bar.

### Is your feature request related to a problem? Please describe. (optional)
No 

### Describe the solution you'd like
I would like to add a animated progress bar in html,css,js

### Describe how this feature will be useful to the users/ contributors-
This can be used in portfolio websites to showcase your skills.

#### Are you contributing under any open-source program ?

Psoc
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by siddhi-244**
## What is the change?
Added Animated Progress Bar. 

## Related issue?
closes: #210 

## How was it tested?
Chrome developer tools 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [] Did you lint and format your code before making the Pull Request?
-   [] Have you made the GIF for the component you added?

## GIF you created:
Add here the GIF you created.

https://user-images.githubusercontent.com/69195262/131789446-7121f4e0-bfd8-441d-ad9e-62a024e037a6.mp4

### CODE REVIEW

**Review by riasenpai — APPROVED** [review]

**Review by theBeginner86 — APPROVED** [review]
Good work 🙌

LGTM 👍

**Comment by siddhi-244** [comment]
> Good work 🙌
> 
> LGTM 👍

Thank you

**Review by Pranav016 — COMMENTED** [review]
Good work

**Comment by Pranav016** [comment]
@riasenpai @theBeginner86 @Ayush0730 thanks for taking over when I wasn't available

**Pull request merged**
