### PR TITLE
Added a new Button to the HTML+CSS+JS section

### PR DESCRIPTION
**Pull request by utkarsh1311**
## What is the change?
Added a new Button to the Buttons section

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

### CODE REVIEW

**Comment by utkarsh1311** [comment]
I have formatted the style.css file using prettier.

**Comment by Ayush0730** [comment]
Changes look good, just add your button in Table Of Content in ```HTML + CSS + JS/README.md``` under buttons

**Review by Ayush0730 — APPROVED** [review]

**Review by Ayush0730 — CHANGES_REQUESTED** [review]
Changes look good, just add your button in Table Of Content in ```HTML+CSS+JS/README.md``` under buttons

**Comment by utkarsh1311** [comment]
I have added my button in the ```HTML+CSS+JS/README.md``` under Buttons section.

**Review by Ayush0730 — APPROVED** [review]

**Pull request merged**
