### PR TITLE
Added Card with Text Animation on Hover to Cards section

### LINKED ISSUE #212: Add Card with Hover animation
### Feature request-
Add a card element which has an animation on hover and show some info.

### Describe how this feature will be useful to the users/ contributors-
Users will be able to use this card in their projects like a recipe or blog card.

### Additional context
This is how the card will look

#### Are you contributing under any open-source program ?

NA
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by utkarsh1311**
## What is the change?
Added Card with Text Animation on Hover to Cards section.

## Related issue?
closes: #212 

## How was it tested?
I have tested this on my local machine.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

## GIF you created:
Add here the GIF you created.
ezgif com-gif-maker

### Please add ```hacktoberfest-accepted``` label to this PR.

### CODE REVIEW

**Review by riasenpai — APPROVED** [review]

**Review by Pranav016 — APPROVED** [review]
LGTM!
It would be great if you could give this animation a specific name because `AnimationOnHoverCard` is a generic name and user cannot identify which animation this would be unless they open the folder. Otherwise also its fine. 

Let me know if these changes sound relevant otherwise I'll merge 👍

**Comment by utkarsh1311** [comment]
If I rename the folder, won't I lose history? Or will this work ```git mv <oldFolder> <newFolder>``` ?

**Comment by Pranav016** [comment]
> If I rename the folder, won't I lose history? Or will this work `git mv <oldFolder> <newFolder>` ?

Yes, just make a new commit after that.
I'll squash the commits before merging.

**Comment by utkarsh1311** [comment]
Ok 👌

**Comment by utkarsh1311** [comment]
All done.

**Review by Pranav016 — APPROVED** [review]

**Pull request merged**
