### PR TITLE
More button animations

### LINKED ISSUE #36: Add button animations
### Feature request-
Add some cool animated button designs to the repository.

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by urvashiparashar**
## What is the change?
Added some button components with animations.

## Related issue?
closes: #36 

## How was it tested?
The html pages were  run on the web browsers like Google chrome, Microsoft edge etc.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

## GIF you created:

AddingButtonComponentAnimations

### CODE REVIEW

**Comment by urvashiparashar** [comment]
I have created an entirely new pull request after editing the changes and closed the previous one. Please consider this one.

**Comment by Ayush0730** [comment]
From next time, don't make multiple commits with same message, and you could have created separate PRs for each button to get more points. 

And do one change, add your buttons in table of content in HTML+CSS+JS/README.md file

**Review by Ayush0730 — CHANGES_REQUESTED** [review]
Rename html files to index.html and css files to style.css (make changes only in the files you created) and add your buttons in 'Table of Content'. Also, run prettifier if you can

**Comment by urvashiparashar** [comment]
I have made the required changes. Please review it.

**Comment by Ayush0730** [comment]
> I have made the required changes. Please review it.

Again you created so many commits

**Comment by Ayush0730** [comment]
My bad, it should be index.html, sorry, can you change all file names again and make just one commit please, and sorry for inconvenience 

> Rename html files to index.js and css files to style.css (make changes only in the files you created) and add your buttons in 'Table of Content'. Also, run prettifier if you can

**Comment by urvashiparashar** [comment]
> > I have made the required changes. Please review it.
> 
> Again you created so many commits

Can you please explain me how to create less number of commits?I am not able to get it.

**Comment by Ayush0730** [comment]
> > > I have made the required changes. Please review it.
> > 
> > 
> > Again you created so many commits
> 
> Can you please explain me how to create less number of commits?I am not able to get it.

Do all the changes then add all files by ```git add file_name``` or you can use ```git add .``` To add all files, and then just create a commit

**Comment by Ayush0730** [comment]
> > > I have made the required changes. Please review it.
> > 
> > 
> > Again you created so many commits
> 
> Can you please explain me how to create less number of commits?I am not able to get it.

If some changes are requested then you can definitely create extra commits, but the number of commits should ideally be 3-4

**Comment by urvashiparashar** [comment]
> > > > I have made the required changes. Please review it.
> > > 
> > > 
> > > Again you created so many commits
> > 
> > 
> > Can you please explain me how to create less number of commits?I am not able to get it.
> 
> If some changes are requested then you can definitely create extra commits, but the number of commits should ideally be 3-4

Sorry , I tried creating one commit for multiple files but changes were not reflected into the branch through which I am making pull request. Please consider it.

**Comment by Ayush0730** [comment]
> > > > > I have made the required changes. Please review it.
> > > > 
> > > > 
> > > > Again you created so many commits
> > > 
> > > 
> > > Can you please explain me how to create less number of commits?I am not able to get it.
> > 
> > 
> > If some changes are requested then you can definitely create extra commits, but the number of commits should ideally be 3-4
> 
> Sorry , I tried creating one commit for multiple files but changes were not reflected into the branch through which I am making pull request. Please consider it.

Okay, no problem, you did a great job, thanks for your contribution.

**Comment by Ayush0730** [comment]
@urvashiparashar why arrowUp.png file is added in root directory? I think you need to delete that

**Comment by urvashiparashar** [comment]
> @urvashiparashar why arrowUp.png file is added in root directory? I think you need to delete that

Now Please check it once I have deleted the file.

**Comment by Pranav016** [comment]
PR is good and ready to be merged, only concern is the number of commits and incorrect commit messages. I advice you to squash the commits with a new commit message and we'll merge it then.

**Comment by urvashiparashar** [comment]
> PR is good and ready to be merged, only concern is the number of commits and incorrect commit messages. I advice you to squash the commits with a new commit message and we'll merge it then.

I tried squashing the commits but wasn't able to do. Pls consider it.

**Review by Pranav016 — APPROVED** [review]

**Review by Ayush0730 — APPROVED** [review]

**Comment by Ayush0730** [comment]
> > PR is good and ready to be merged, only concern is the number of commits and incorrect commit messages. I advice you to squash the commits with a new commit message and we'll merge it then.
> 
> I tried squashing the commits but wasn't able to do. Pls consider it.

No problem, you have done a good work.

From next time keep these points in mind
- Create less number of commits
- Write good commit messages

**Comment by Pranav016** [comment]
@all-contributors please add @urvashiparashar for code

**Comment by Pranav016** [comment]
@all-contributors please add @urvashiparashar for doc

**Pull request merged**
