### PR TITLE
Added Scroll to Top Button 

### LINKED ISSUE #16: Add scroll to top button component
### Feature request-
Add scroll to top button component that scrolls up for you when you are in the middle or at the end of a page.
Like one on this website- https://word-nook.herokuapp.com/

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by Anupam-Panwar**
## What is the change?
* Added a folder named scrollToTopButton in HTML+CSS+JS/Buttons
* Folder contains all the files required to use that component in the project

## Related issue?
closes: #16 

## How was it tested?
* Code was tested thoroughly in Desktop and Mobile using Chrome borwser

## Checklist:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

## GIF you created:
gif

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Great work, 
Some suggestions-
- Next time make PR from a new branch.
- Try to solve issue within 3 to 4 commits unless absolutely necessary.
- Divide the main div into 3-4 divs with difference color backgrounds so that we can see that you are scrolling. Currently in the GIF we cannot identify if you are scrolling. [Example](https://github.com/ALPHAVIO/Mirage-UI/tree/master/HTML%2BCSS%2BJS/Background/SmoothScroll)

I think the PR is good and ready to merge but if you can solve the background issue so that scrolling is visible then that would be great.

**Comment by Anupam-Panwar** [comment]
@Pranav016 I will update the PR asap

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
Good work, next time try to do it in less no of commits 👍

**Comment by Anupam-Panwar** [comment]
> Good work, next time try to do it in less no of commits 👍

Sure

**Comment by Pranav016** [comment]
@all-contributors please add @Anupam-Panwar for code, doc

**Comment by Pranav016** [comment]
@all-contributors please add @Anupam-Panwar for code

**Comment by Pranav016** [comment]
@all-contributors please add @Anupam-Panwar for doc

**Pull request merged**
