### PR TITLE
Added Logo

### LINKED ISSUE #8: Make a logo for `Mirage UI`
### Feature request-
Make a logo for `Mirage UI`.  Using the text only `Mirage UI`, make a very small logo with of styled wordings. I think rainbow style would look good but you can make multiple styles and we can chose between them.

Also I saw a logo the other day that was rainbow text and had some animation to it (probably a GIF), something of that sort would also look good. 

Maybe a small logo along with the styled wordings might also look good.
Sample logo of material UI- 
image

I'd advice to take this issue only if you are creative and good with designing and can make a few samples before we can decide one.

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by Manasa2811**
## What is the change?
Added the logo to the project README. Renamed the Assets folder to assets. Removed extra README

## Related issue?
closes: #8 

## How was it tested?
The logo was approved before i created the pull request.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

## GIF you created:
MIRAGE

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Replace heading Mirage UI at the top of project README with this logo.

Also name the folder `assets` instead of `Logo`, so we can keep all assets of the project in one folder

**Comment by Manasa2811** [comment]
Done

**Comment by Pranav016** [comment]
- You don't need to add a README for logo, its not a code component. You can remove it
- Rename folder to `assets` instead of `Assets` according to the convention
-  If you have added the logo to assets folder then you can add it to project README like this- 
`Logo`

**Comment by Ayush0730** [comment]
One more change is required, change name of folder from `Assets` to `assets`

**Comment by Manasa2811** [comment]
I've done the changes, however I couldnt change the link of the gif in the README as it was not loading. So I left it like that itself.

**Comment by theBeginner86** [comment]
> I've done the changes, however I couldnt change the link of the gif in the README as it was not loading. So I left it like that itself.

No problem we will do the rest of it for you. 🙂

**Review by theBeginner86 — APPROVED** [review]

**Pull request merged**
