### PR TITLE
updated readme with opensource program

### LINKED ISSUE #146: Add an Open-Source event section to README
### Feature request-
Add an Open-Source event associated section to README
For example-
image
(You can get markdown code for this section from here - https://github.com/ALPHAVIO/WordNook)

Currently this project is associated with LGM-SOC and PSoC thus add their image and some info about them.

LGM-SOC
<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by jay-2000**
## What is the change?
added LGM-SOC  and JWOC program in brief with their program logo/images

closes: #146

### CODE REVIEW

**Comment by Ayush0730** [comment]
Please read the issue description again, it was to add LGM-SOC and PSOC(Pclub summer of code). Remove JWOC

Correct the Spelling mistake in LGM-SOC

And you should raise a PR from new branch (not master), please keep this in mind from next time

**Review by Pranav016 — CHANGES_REQUESTED** [review]
You can replace JWoC with PSoC.
Find info about psoc from here - https://www.pclubsummerofcode.in/#

**Comment by jay-2000** [comment]
> Please read the issue description again, it was to add LGM-SOC and PSOC(Pclub summer of code). Remove JWOC
> 
> Correct the Spelling mistake in LGM-SOC
> 
> And you should raise a PR from new branch (not master), please keep this in mind from next time

thank you , for reminding me what that BRANCH - PR , i will surely do it properly
closes #148

**Review by Pranav016 — APPROVED** [review]
Too many commits with some incorrect commit messages, keep in mind for next time.
Also the branch

**Comment by Pranav016** [comment]
@jay-2000 move this open-source section above the contribution graph and contributors section then I'll merge 👍

**Comment by jay-2000** [comment]
> @jay-2000 move this open-source section above the contribution graph and contributors section then I'll merge 👍

should I put exactly above maintainer part @Pranav016

**Comment by Pranav016** [comment]
> > @jay-2000 move this open-source section above the contribution graph and contributors section then I'll merge 👍
> 
> should I put exactly above maintainer part @Pranav016

Yes

**Comment by jay-2000** [comment]
> > > @jay-2000 move this open-source section above the contribution graph and contributors section then I'll merge 👍
> > 
> > 
> > should I put exactly above maintainer part @Pranav016
> 
> Yes

done , Thank you  for the guidance

**Comment by jay-2000** [comment]
> > > > @jay-2000 move this open-source section above the contribution graph and contributors section then I'll merge 👍
> > > 
> > > 
> > > should I put exactly above maintainer part @Pranav016
> > 
> > 
> > Yes
> 
> done , Thank you for the guidance

do let me know if any changes are required in it @Pranav016

**Comment by Pranav016** [comment]
@all-contributors please add @jay-2000 for doc

**Pull request merged**
