### PR TITLE
code for card pop up animation on hover

### PR DESCRIPTION
**Pull request by bhoskarpooja**
## What is the change?
I have added proper code for card popup animation oh hover which will show info on hover.

## Related issue?
#44 

## How was it tested?
I tested this on localhost.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing. YEs
-   [] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change? YAS
-   [] Have you made corresponding changes to the documentation? YES
-   [] Have you tested the code before submission?YES
-   [] Did you lint and format your code before making the Pull Request? YES
-   [] Have you made the GIF for the component you added? YES

## GIF you created:
cardhover

### CODE REVIEW

**Review by Pranav016 — CHANGES_REQUESTED** [review]
Great work :+1: 
add the component name to this index as well- https://github.com/ALPHAVIO/Mirage-UI/blob/master/HTML%2BCSS%2BJS/README.md

Also add your name as Author in the README  you created for this component.
` HTML+CSS+JS/Cards/Card Pop up on hover/README.md` -> this file

**Comment by bhoskarpooja** [comment]
I have added Corrections but now how can i PR? its directly showing view pull request. That Means i have done changes ?? Ahead my previous ones ?

**Comment by theBeginner86** [comment]
> I have added Corrections but now how can i PR? its directly showing view pull request. That Means i have done changes ?? Ahead my previous ones ?

Yeah, your changes came!!
when you add more commits and push through the branch linked to the same unmerged PR, then it gets added on the top of previous ones automatically.

You may check it out yourself under the files changes section. Here: https://github.com/ALPHAVIO/Mirage-UI/pull/61/files

**Comment by Pranav016** [comment]
@theBeginner86 you can approve and merge it now 👍

**Review by theBeginner86 — APPROVED** [review]
Great Work 🙌

**Comment by Pranav016** [comment]
@all-contributors please add @bhoskarpooja for code

**Comment by Pranav016** [comment]
@all-contributors please add @bhoskarpooja for doc

**Comment by bhoskarpooja** [comment]
Thank You...😊

**Pull request merged**
