### PR TITLE
Akshikamudgal patch 1

### LINKED ISSUE #11: Add background motion effect component
### Feature request-
Add a simple and easy to use background motion effect component.

https://user-images.githubusercontent.com/54665036/120937593-03224c80-c72c-11eb-9915-727b138c939e.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by akshikamudgal**
##What is the change?

Added a folder named background-effect in HTML+CSS

##Related issue?
closes: #11

##How was it tested?
Code was tested thoroughly in Desktop using microsoft edge

##Checklist:

- [x]  Have you followed the Contribution Guidelines while contributing.
- [x]  Have you checked there aren't other open Pull Requests for the same update/change?
- [x]  Have you made corresponding changes to the documentation?
- [x]  Have you tested the code before submission?
- [x]  Did you lint and format your code before making the Pull Request?
- [x]  Have you made the GIF for the component you added?

##GIF/video you created:
image

### CODE REVIEW

**Comment by akshikamudgal** [comment]
I have created through new branch but still it is merging with other one I am not getting how to fix it.

**Review by Pranav016 — APPROVED** [review]

**Comment by akshikamudgal** [comment]
Merged in the project but still not got my name as a contributor. why?

**Comment by Pranav016** [comment]
@all-contributors please add @akshikamudgal for code

**Comment by akshikamudgal** [comment]
Merged in the project but still not got my name as a contributor. why? @Pranav016

**Comment by Pranav016** [comment]
> Merged in the project but still not got my name as a contributor. why? @Pranav016

Did not add all at once, was going to add more contributors today

**Comment by Pranav016** [comment]
@all-contributors please add @akshikamudgal for doc

**Pull request merged**
