### PR TITLE
 button animations

### LINKED ISSUE #36: Add button animations
### Feature request-
Add some cool animated button designs to the repository.

LGM-SOC

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by urvashiparashar**
## What is the change?
 Added animations to the buttons in the repo

## Related issue?
closes: #36 

## How was it tested?
The html files were being run on the browsers.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [] Did you lint and format your code before making the Pull Request?
-   [] Have you made the GIF for the component you added?

## GIF you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by urvashiparashar** [comment]
Please review it.

**Comment by Ayush0730** [comment]
I think you misunderstood the issue, the issue was to just add a new button component with animation. You don't have to modify other buttons.

**Comment by urvashiparashar** [comment]
> I think you misunderstood the issue, the issue was to just add a new button component with animation. You don't have to modify other buttons.

 Okay. So should I close this pull request and create a new one after editing?

**Comment by Ayush0730** [comment]
> > I think you misunderstood the issue, the issue was to just add a new button component with animation. You don't have to modify other buttons.
> > Okay. So should I close this pull request and create a new one after editing?

You can wait for the response from Project Admin @Pranav016

**Comment by Pranav016** [comment]
Yes, you can close this and create a new one. You can either copy this code to a new folder in Buttons to create a new animation or start from scratch to add new animations in a new folder inside the Buttons folder.

Also revert the changes made to these files.

**Comment by Pranav016** [comment]
Also make PR from a new branch

**Pull request closed without merging**
