### PR TITLE
Flip card animation added

### LINKED ISSUE #9: Add card flip animation component
# Feature request-
Add card flip animation component.

https://user-images.githubusercontent.com/54665036/120903615-bcb5ea80-c664-11eb-8068-fc09da2f1b13.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
## What is the change?
I have added the flip card animation in the cards folder.

## Related issue?
Fixes #9 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

GIF-
mirage

### CODE REVIEW

**Comment by Khushi-agarwal** [comment]
@Pranav016 kindly review it.

**Review by Pranav016 — CHANGES_REQUESTED** [review]
- Add a README for your component, you can use this template to make a README for your component- [README Template](https://github.com/ALPHAVIO/Mirage-UI/blob/master/README_TEMPLATE.md) (Also go through the instructions in the [README](https://github.com/ALPHAVIO/Mirage-UI))
- The commit message is incorrect, please write good commit messages like `Add Flip-Animation card component` etc.
- The cards in the demo video you added have no boundary so its hard to identify them, make the cards like in the demo we have in the issue description of #9 . Maybe adding an image front side of card would look better.

**Comment by Khushi-agarwal** [comment]
@Pranav016 Its done now.Kindly review it.
flipcard

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
It's ready to be merged, one more addition. Update this index- [Mirage-UI/HTML+CSS+JS/README.md](https://github.com/ALPHAVIO/Mirage-UI/blob/master/HTML%2BCSS%2BJS/README.md)

**Comment by Khushi-agarwal** [comment]
> It's ready to be merged, one more addition. Update this index- [Mirage-UI/HTML+CSS+JS/README.md](https://github.com/ALPHAVIO/Mirage-UI/blob/master/HTML%2BCSS%2BJS/README.md)

Its updated now @Pranav016 .

**Pull request merged**
