### PR TITLE
carousel component added

### PR DESCRIPTION
**Pull request by Sanyam17-beep**
## What is the change?
Card Carousel feature added

## Related issue?
#42 

https://user-images.githubusercontent.com/84903641/122436072-2663bc00-cfb6-11eb-91fd-ee2d8cd47b30.mp4

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [] Have you made corresponding changes to the documentation?
-   [] Have you tested the code before submission?
-   [] Did you lint and format your code before making the Pull Request?
-   [] Have you made the GIF for the component you added?

## GIF you created:
Add here the GIF you created.

### CODE REVIEW

**Review by theBeginner86 — CHANGES_REQUESTED** [review]
Please improve this PR by:
- adding the GIF of your feature.
- writing the issue number.
> Try to follow the PR template as much as possible

#### Also, you didn't add the README.md file for your component under 
`Mirage-UI/HTML+CSS+JS/Cards/Carouselcomponent` 
#### and your component link under the cards list at 
`Mirage-UI/HTML+CSS+JS/README.md`

Please do the above changes so that reviewing process becomes easier for us.


You can always take references from previously merged PR.
https://github.com/ALPHAVIO/Mirage-UI/pull/61

**Comment by Sanyam17-beep** [comment]
is it okay now responsive carousel feature added

**Review by theBeginner86 — CHANGES_REQUESTED** [review]
Great Work👍

Just do a few more things. You need to add a link to your component under the list of components at `HTML+CSS+JS/README.md` and rename your README file `HTML+CSS+JS/Cards/Carouselcomponent/Readme.md --> HTML+CSS+JS/Cards/Carouselcomponent/README.md` 

The name of the README file needs to be changed so that git can recognize it.

Let us know if you need any help for doing the changes.🙂

**Comment by theBeginner86** [comment]
Suggestion:

- For adding a link, you can use: `-   [Carousel](Cards/Carouselcomponent)`. You need to use this under the Cards section list of `HTML+CSS+JS/README.md`

#### Do test it once before pushing 👍

**Comment by Sanyam17-beep** [comment]
i have done that and thank you for your every help

**Comment by theBeginner86** [comment]
@Sanyam17-beep, Everything seems fine now. 
Just wait for some more time till PA have look into it. Then we would merge it.

You did a great job. Keep it up 🎊 🙌
> I know this is your first-ever PR

**Review by Pranav016 — APPROVED** [review]

**Comment by Pranav016** [comment]
@all-contributors please add @Sanyam17-beep for code

**Comment by Pranav016** [comment]
@all-contributors please add @Sanyam17-beep for doc

**Pull request merged**
