### PR TITLE
Dynamic-wave-background

### LINKED ISSUE #12: Add dynamic wave component
### Feature request-

https://user-images.githubusercontent.com/54665036/120938947-07059d00-c733-11eb-852e-dd941af2a81e.mp4

<hr/>

**Note:**

-   If you want to work on an issue, you should check if it has already been assigned to anyone. **If the issue is free** you can comment `/assign` to get the issue assigned to you.
-   If you are raising a new issue and want to work on it then also you should comment `/assign` under the issue to get it auto assigned.
- It is adviced to take up/ work on only 2 issues at the same time.
-   Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.

### PR DESCRIPTION
**Pull request by Sanyam17-beep**
## What is the change?
Dynamic-wave-background

## Related issue?
#12 

https://user-images.githubusercontent.com/84903641/128697495-3b88180e-0755-4a6d-80ea-dfe3eae90866.mp4

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [] Have you made corresponding changes to the documentation?
-   [] Have you tested the code before submission?
-   [] Did you lint and format your code before making the Pull Request?
-   [] Have you made the GIF for the component you added?

## GIF you created:
Add here the GIF you created.

### CODE REVIEW

**Comment by Sanyam17-beep** [comment]
hey @Pranav016 and @theBeginner86 HOW WOULD I KNOW HOW MANY PR WERE MERGED BY ME

**Comment by theBeginner86** [comment]
> hey @Pranav016 and @theBeginner86 HOW WOULD I KNOW HOW MANY PR WERE MERGED BY ME

See every PR made by LGM-SOC'21 participant, has two tags: LGM-SOC and level. These would be mapped by LGM-SOC organizers during points calculation of each project and depending upon the no of PRs and level of each PR (the level tag tells this) your final score would be calculated.
Still, if you want to check, then you can go to the merged section of PR for this project and see all the PRs merged by you. Right now you have successfully merged `12 PRs` for this project.

Use this link: https://github.com/ALPHAVIO/Mirage-UI/pulls?q=is%3Apr+author%3ASanyam17-beep
It would show you all the PRs raised by you for this project.

**Review by theBeginner86 — APPROVED** [review]
LGTM. 👍

**Review by Pranav016 — COMMENTED** [review]
Good work

**Pull request merged**
